-- 初始化数据库表结构
-- 启用 TimescaleDB 扩展
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- 电价数据表
CREATE TABLE IF NOT EXISTS lmp_data (
    id SERIAL,
    node_id VARCHAR(50) NOT NULL,
    market_type VARCHAR(10) NOT NULL,
    interval_start TIMESTAMPTZ NOT NULL,
    interval_end TIMESTAMPTZ NOT NULL,
    price DECIMAL(10, 4) NOT NULL,
    mw DECIMAL(10, 4),
    group_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id, interval_start)
);

-- 转换为超表（时序数据优化）
SELECT create_hypertable('lmp_data', 'interval_start', 
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_lmp_node_market ON lmp_data (node_id, market_type, interval_start DESC);
CREATE INDEX IF NOT EXISTS idx_lmp_interval ON lmp_data (interval_start DESC);

-- 系统负荷数据表
CREATE TABLE IF NOT EXISTS system_demand (
    id SERIAL,
    interval_start TIMESTAMPTZ NOT NULL,
    demand_mw DECIMAL(10, 2),
    forecast_mw DECIMAL(10, 2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id, interval_start)
);

SELECT create_hypertable('system_demand', 'interval_start',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE
);

-- 交易信号记录表
CREATE TABLE IF NOT EXISTS trading_signals (
    id SERIAL,
    timestamp TIMESTAMPTZ NOT NULL,
    node_id VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,  -- CHARGE, DISCHARGE, HOLD
    price DECIMAL(10, 4) NOT NULL,
    quantity_mw DECIMAL(10, 4),
    reason TEXT,
    executed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id, timestamp)
);

SELECT create_hypertable('trading_signals', 'timestamp',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE
);

-- 统计数据缓存表（用于快速查询）
CREATE TABLE IF NOT EXISTS price_statistics (
    id SERIAL PRIMARY KEY,
    node_id VARCHAR(50) NOT NULL,
    market_type VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    min_price DECIMAL(10, 4),
    max_price DECIMAL(10, 4),
    avg_price DECIMAL(10, 4),
    std_price DECIMAL(10, 4),
    total_volume DECIMAL(15, 4),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(node_id, market_type, date)
);

-- 创建更新统计数据的函数
CREATE OR REPLACE FUNCTION update_daily_stats()
RETURNS void AS $$
BEGIN
    INSERT INTO price_statistics (node_id, market_type, date, min_price, max_price, avg_price, std_price, total_volume)
    SELECT 
        node_id,
        market_type,
        DATE(interval_start) as date,
        MIN(price) as min_price,
        MAX(price) as max_price,
        AVG(price) as avg_price,
        STDDEV(price) as std_price,
        COUNT(*) as total_volume
    FROM lmp_data
    WHERE interval_start >= CURRENT_DATE - INTERVAL '1 day'
    GROUP BY node_id, market_type, DATE(interval_start)
    ON CONFLICT (node_id, market_type, date) 
    DO UPDATE SET
        min_price = EXCLUDED.min_price,
        max_price = EXCLUDED.max_price,
        avg_price = EXCLUDED.avg_price,
        std_price = EXCLUDED.std_price,
        total_volume = EXCLUDED.total_volume,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- 创建连续聚合视图（实时统计）
CREATE MATERIALIZED VIEW IF NOT EXISTS lmp_hourly_stats
WITH (timescaledb.continuous) AS
SELECT 
    time_bucket('1 hour', interval_start) as bucket,
    node_id,
    market_type,
    AVG(price) as avg_price,
    MIN(price) as min_price,
    MAX(price) as max_price,
    STDDEV(price) as std_price,
    COUNT(*) as count
FROM lmp_data
GROUP BY bucket, node_id, market_type
WITH NO DATA;

-- 设置连续聚合刷新策略
SELECT add_continuous_aggregate_policy('lmp_hourly_stats',
    start_offset => INTERVAL '1 month',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '5 minutes'
);

-- 添加注释
COMMENT ON TABLE lmp_data IS 'CAISO Locational Marginal Price data';
COMMENT ON TABLE system_demand IS 'CAISO System demand and forecast data';
COMMENT ON TABLE trading_signals IS 'Trading signals generated by strategies';
COMMENT ON TABLE price_statistics IS 'Daily aggregated price statistics';